server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mariamabidi
    username: mariamabidi
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mySecretKey
  expirationMs: 86400000  # Token expires in 1 day

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
