server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mariamabidi
    username: mariamabidi
    password: None
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mySecretKey
  expirationMs: 86400000  # Token expires in 1 day
