server:
  port: 8083  # Different from User Service & Product Service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: mariamabidi
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Creates tables automatically
    show-sql: true      # Logs SQL queries

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
